
export const pages = [
"attributions", 
"contribution", 
"description", 
"engineering", 
// "hardware", 
"human-practices", 
"inclusivity", 
"model", 
"rca-optimization", 
"rca-expansion",
"saftey", 
"parts-library", 
"parts-collection", 
"notebook", 
"results", 
"contribution", 
"protein-purification", 
"experiments", 
"measurement",
"poc",
"hardware",
"software"];